<a href="https://colab.research.google.com/github/Sarasii22/Sleep-Quality-Prediction-Using-Lifestyle-Factors/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Sleep Quality Prediction using Lifestyle Factors

This notebook implements a machine learning project to predict 'Quality of Sleep' using various lifestyle factors. We will use Logistic Regression and K-Nearest Neighbors (KNN) algorithms for this multi-class classification task.

### 1. Data Loading and Initial Exploration

In [26]:
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
# import seaborn as sns
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder, StandardScaler
# from sklearn.linear_model import LogisticRegression
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [27]:
# Mount Google Drive to access the dataset
from google.colab import drive
drive.mount('/content/drive')

# Load the dataset
data = pd.read_csv("/content/drive/MyDrive/ML_project/Sleep_health_and_lifestyle_dataset.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
data.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [30]:
data.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [31]:
data.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

### 2. Data Cleaning and Preprocessing

In [32]:
data = data.drop(['Person ID'], axis=1)
print("DataFrame after dropping 'Person ID':")
data.head()

DataFrame after dropping 'Person ID':

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [34]:
# Split 'Blood Pressure' into 'Systolic' and 'Diastolic'
data[['Systolic', 'Diastolic']] = data['Blood Pressure'].str.split('/', expand=True)

In [35]:
# Convert 'Systolic' and 'Diastolic' to integer type
data['Systolic'] = data['Systolic'].astype(int)
data['Diastolic'] = data['Diastolic'].astype(int)

In [36]:
# Drop the original 'Blood Pressure' column
data = data.drop('Blood Pressure', axis=1)
print("\nDataFrame after processing 'Blood Pressure':")
data.head()

DataFrame after processing 'Blood Pressure':

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic,Diastolic
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,NaN,126,83
1,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125,80
2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125,80
3,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90
4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90

In [37]:
# Label Encode 'Gender'
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])
print("\nDataFrame after Label Encoding 'Gender':")
display(data.head())

# male - 1  female - 0

DataFrame after Label Encoding 'Gender':

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic,Diastolic
0,1,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,NaN,126,83
1,1,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125,80
2,1,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125,80
3,1,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90
4,1,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90

In [38]:
# Perform one-hot encoding for 'Occupation' and 'BMI Category'
data = pd.get_dummies(data, columns=['Occupation', 'BMI Category'], drop_first=True, dtype=int)

print("DataFrame after One-Hot Encoding 'Occupation' and 'BMI Category':")
display(data.head())
print("\nUpdated DataFrame shape:", data.shape)

DataFrame after One-Hot Encoding 'Occupation' and 'BMI Category':

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder,Systolic,...,Occupation_Manager,Occupation_Nurse,Occupation_Sales Representative,Occupation_Salesperson,Occupation_Scientist,Occupation_Software Engineer,Occupation_Teacher,BMI Category_Normal Weight,BMI Category_Obese,BMI Category_Overweight
0,1,27,6.1,6,42,6,77,4200,NaN,126,...,0,0,0,0,0,1,0,0,0,1
1,1,28,6.2,6,60,8,75,10000,NaN,125,...,0,0,0,0,0,0,0,0,0,0
2,1,28,6.2,6,60,8,75,10000,NaN,125,...,0,0,0,0,0,0,0,0,0,0
3,1,28,5.9,4,30,8,85,3000,Sleep Apnea,140,...,0,0,1,0,0,0,0,0,1,0
4,1,28,5.9,4,30,8,85,3000,Sleep Apnea,140,...,0,0,1,0,0,0,0,0,1,0

Updated DataFrame shape: (374, 24)

### 3. Define Target Variable for Specific Sleep Disorder Prediction

In [39]:
# Fill NaN values in 'Sleep Disorder' with 'None' to create a multi-class target
data['Sleep Disorder'] = data['Sleep Disorder'].fillna('None')

In [40]:
# Label Encode the 'Sleep Disorder' column to numerical values
from sklearn.preprocessing import LabelEncoder
mapping = {
    'None': 0,
    'Insomnia': 1,
    'Sleep Apnea': 2
}
data['Sleep Disorder Encoded'] = data['Sleep Disorder'].map(mapping)

In [41]:
print("DataFrame with new multi-class target 'Sleep Disorder Encoded':")
print(data[['Sleep Disorder', 'Sleep Disorder Encoded']].head(10))
print("\nMapping of encoded labels:")
for key, value in mapping.items():
    print(f"{key}: {value}")

DataFrame with new multi-class target 'Sleep Disorder Encoded':
  Sleep Disorder  Sleep Disorder Encoded
0           None                       0
1           None                       0
2           None                       0
3    Sleep Apnea                       2
4    Sleep Apnea                       2
5       Insomnia                       1
6       Insomnia                       1
7           None                       0
8           None                       0
9           None                       0

Mapping of encoded labels:
None: 0
Insomnia: 1
Sleep Apnea: 2

### 3.2 Define Features (X) and Multi-class Target (y)

In [42]:
# Define features (X) by dropping original target candidates and ID columns
# 'Quality of Sleep' is also dropped as it's not our current prediction target
X = data.drop(['Quality of Sleep', 'Sleep Disorder', 'Sleep Disorder Encoded'], axis=1)
y = data['Sleep Disorder Encoded']

print("Features (X) head:")
display(X.head())
print("\nTarget (y) head:")
display(y.head())
print("\nValue counts for new target (y):")
display(y.value_counts())

Features (X) head:

,Gender,Age,Sleep Duration,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Systolic,Diastolic,Occupation_Doctor,...,Occupation_Manager,Occupation_Nurse,Occupation_Sales Representative,Occupation_Salesperson,Occupation_Scientist,Occupation_Software Engineer,Occupation_Teacher,BMI Category_Normal Weight,BMI Category_Obese,BMI Category_Overweight
0,1,27,6.1,42,6,77,4200,126,83,0,...,0,0,0,0,0,1,0,0,0,1
1,1,28,6.2,60,8,75,10000,125,80,1,...,0,0,0,0,0,0,0,0,0,0
2,1,28,6.2,60,8,75,10000,125,80,1,...,0,0,0,0,0,0,0,0,0,0
3,1,28,5.9,30,8,85,3000,140,90,0,...,0,0,1,0,0,0,0,0,1,0
4,1,28,5.9,30,8,85,3000,140,90,0,...,0,0,1,0,0,0,0,0,1,0

Target (y) head:

0    0
1    0
2    0
3    2
4    2
Name: Sleep Disorder Encoded, dtype: int64

Value counts for new target (y):

Sleep Disorder Encoded
0    219
2     78
1     77
Name: count, dtype: int64

### 4. Train-Test Split and Feature Scaling

In [43]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y) # Stratify to maintain class distribution

In [44]:
# Initialize StandardScaler and scale the features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [45]:
print("Shape of X_train_scaled:", X_train_scaled.shape)
print("Shape of X_test_scaled:", X_test_scaled.shape)

Shape of X_train_scaled: (299, 22)
Shape of X_test_scaled: (75, 22)

In [46]:
# Check the distribution of y_train and y_test to ensure stratification worked
print("\nDistribution of 'Sleep Disorder Encoded' in y_train:")
display(y_train.value_counts(normalize=True).sort_index())
print("\nDistribution of 'Sleep Disorder Encoded' in y_test:")
display(y_test.value_counts(normalize=True).sort_index())

Distribution of 'Sleep Disorder Encoded' in y_train:

Sleep Disorder Encoded
0    0.585284
1    0.207358
2    0.207358
Name: proportion, dtype: float64

Distribution of 'Sleep Disorder Encoded' in y_test:

Sleep Disorder Encoded
0    0.586667
1    0.200000
2    0.213333
Name: proportion, dtype: float64

In [47]:
print(data.isnull().sum())

Gender                             0
Age                                0
Sleep Duration                     0
Quality of Sleep                   0
Physical Activity Level            0
Stress Level                       0
Heart Rate                         0
Daily Steps                        0
Sleep Disorder                     0
Systolic                           0
Diastolic                          0
Occupation_Doctor                  0
Occupation_Engineer                0
Occupation_Lawyer                  0
Occupation_Manager                 0
Occupation_Nurse                   0
Occupation_Sales Representative    0
Occupation_Salesperson             0
Occupation_Scientist               0
Occupation_Software Engineer       0
Occupation_Teacher                 0
BMI Category_Normal Weight         0
BMI Category_Obese                 0
BMI Category_Overweight            0
Sleep Disorder Encoded             0
dtype: int64

### 5. Model Training and Evaluation - Logistic Regression (Multi-class)

In [48]:
# Initialize and train the Logistic Regression model for multi-class classification
# 'newton-cg' or 'lbfgs' are suitable for multi_class='multinomial'
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

In [50]:
y_train_pred_lr = lr.predict(X_train_scaled)
y_test_pred_lr = lr.predict(X_test_scaled)

In [51]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("=== Logistic Regression ===")

print("\n--- Train Data ---")
print("Accuracy:", accuracy_score(y_train, y_train_pred_lr))
print("Precision:", precision_score(y_train, y_train_pred_lr, average='weighted'))
print("Recall:", recall_score(y_train, y_train_pred_lr, average='weighted'))
print("F1 Score:", f1_score(y_train, y_train_pred_lr, average='weighted'))

print("\n--- Test Data ---")
print("Accuracy:", accuracy_score(y_test, y_test_pred_lr))
print("Precision:", precision_score(y_test, y_test_pred_lr, average='weighted'))
print("Recall:", recall_score(y_test, y_test_pred_lr, average='weighted'))
print("F1 Score:", f1_score(y_test, y_test_pred_lr, average='weighted'))

=== Logistic Regression ===

--- Train Data ---
Accuracy: 0.9297658862876255
Precision: 0.9297401149017241
Recall: 0.9297658862876255
F1 Score: 0.9294748974925835

--- Test Data ---
Accuracy: 0.8666666666666667
Precision: 0.8819172113289762
Recall: 0.8666666666666667
F1 Score: 0.8718674136321196

### 6. Model Training and Evaluation - K-Nearest Neighbors (KNN) (Multi-class)

In [52]:
# Initialize and train the KNN model for multi-class classification
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

In [53]:
y_train_pred_knn = knn.predict(X_train_scaled)
y_test_pred_knn = knn.predict(X_test_scaled)

In [54]:
print("\n=== KNN ===")

print("\n--- Train Data ---")
print("Accuracy:", accuracy_score(y_train, y_train_pred_knn))
print("Precision:", precision_score(y_train, y_train_pred_knn, average='weighted'))
print("Recall:", recall_score(y_train, y_train_pred_knn, average='weighted'))
print("F1 Score:", f1_score(y_train, y_train_pred_knn, average='weighted'))

print("\n--- Test Data ---")
print("Accuracy:", accuracy_score(y_test, y_test_pred_knn))
print("Precision:", precision_score(y_test, y_test_pred_knn, average='weighted'))
print("Recall:", recall_score(y_test, y_test_pred_knn, average='weighted'))
print("F1 Score:", f1_score(y_test, y_test_pred_knn, average='weighted'))

=== KNN ===

--- Train Data ---
Accuracy: 0.9130434782608695
Precision: 0.9133511772143277
Recall: 0.9130434782608695
F1 Score: 0.9122628526669156

--- Test Data ---
Accuracy: 0.84
Precision: 0.8573594771241829
Recall: 0.84
F1 Score: 0.8461760461760462

### 7. Model Comparison and User Prediction Function